"""empty message

Revision ID: 0ca18b041472
Revises: 31306f7b8b19
Create Date: 2026-01-12 11:39:22.288898

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ca18b041472'
down_revision = '31306f7b8b19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alert_events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active_key', sa.String(length=64), nullable=True))
        batch_op.create_index(batch_op.f('ix_alert_events_active_key'), ['active_key'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alert_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alert_events_active_key'))
        batch_op.drop_column('active_key')

    # ### end Alembic commands ###
