"""empty message

Revision ID: 1dd468eebc38
Revises: 5e55119daa6f
Create Date: 2025-12-29 14:19:27.903251

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1dd468eebc38'
down_revision = '5e55119daa6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('danger_score',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dangerScore', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alert_events', schema=None) as batch_op:
        batch_op.alter_column('level',
               existing_type=mysql.ENUM('EMERGENCY', 'NORMAL', 'WARNING'),
               type_=sa.Enum('NORMAL', 'WARNING', 'EMERGENCY', name='alert_level'),
               existing_nullable=False)
        batch_op.drop_index(batch_op.f('idx_alert_ack'))
        batch_op.drop_index(batch_op.f('idx_alert_ended'))
        batch_op.drop_index(batch_op.f('idx_alert_level'))
        batch_op.drop_index(batch_op.f('idx_alert_machine'))
        batch_op.drop_index(batch_op.f('idx_alert_started'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alert_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_alert_started'), ['started_at'], unique=False)
        batch_op.create_index(batch_op.f('idx_alert_machine'), ['machine_number'], unique=False)
        batch_op.create_index(batch_op.f('idx_alert_level'), ['level'], unique=False)
        batch_op.create_index(batch_op.f('idx_alert_ended'), ['ended_at'], unique=False)
        batch_op.create_index(batch_op.f('idx_alert_ack'), ['acknowledged_at'], unique=False)
        batch_op.alter_column('level',
               existing_type=sa.Enum('NORMAL', 'WARNING', 'EMERGENCY', name='alert_level'),
               type_=mysql.ENUM('EMERGENCY', 'NORMAL', 'WARNING'),
               existing_nullable=False)

    op.drop_table('danger_score')
    # ### end Alembic commands ###
