"""empty message

Revision ID: 255b2129fe2d
Revises: 
Create Date: 2025-12-29 16:55:10.293798

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '255b2129fe2d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('machines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alert_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('machine_number', sa.Integer(), nullable=True),
    sa.Column('level', sa.Enum('NORMAL', 'WARNING', 'EMERGENCY', name='alert_level'), nullable=False),
    sa.Column('danger_score', sa.Float(), nullable=True),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('message', sa.String(length=255), nullable=False),
    sa.Column('snapshot', mysql.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['machine_number'], ['machines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alert_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alert_events_acknowledged_at'), ['acknowledged_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_alert_events_ended_at'), ['ended_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_alert_events_level'), ['level'], unique=False)
        batch_op.create_index(batch_op.f('ix_alert_events_machine_number'), ['machine_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_alert_events_started_at'), ['started_at'], unique=False)

    op.create_table('danger_score',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dangerScore', sa.Float(), nullable=False),
    sa.Column('machine_number', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['machine_number'], ['machines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('defects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('defect_type', sa.Enum('Label', 'Crushed', 'Discolored', 'weight', name='defect_types'), nullable=True),
    sa.Column('machine_number', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['machine_number'], ['machines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rejection_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('rejection_rate', sa.Double(), nullable=True),
    sa.Column('total_inspected', sa.Integer(), nullable=True),
    sa.Column('total_rejected', sa.Integer(), nullable=True),
    sa.Column('machine_number', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['machine_number'], ['machines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sensors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('machine_number', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('temperature_DS18B20', sa.Float(), nullable=True),
    sa.Column('humidity', sa.Float(), nullable=True),
    sa.Column('noise', sa.Float(), nullable=True),
    sa.Column('leak', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['machine_number'], ['machines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sensors')
    op.drop_table('rejection_rates')
    op.drop_table('defects')
    op.drop_table('danger_score')
    with op.batch_alter_table('alert_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alert_events_started_at'))
        batch_op.drop_index(batch_op.f('ix_alert_events_machine_number'))
        batch_op.drop_index(batch_op.f('ix_alert_events_level'))
        batch_op.drop_index(batch_op.f('ix_alert_events_ended_at'))
        batch_op.drop_index(batch_op.f('ix_alert_events_acknowledged_at'))

    op.drop_table('alert_events')
    op.drop_table('machines')
    # ### end Alembic commands ###
