"""empty message

Revision ID: 31306f7b8b19
Revises: 255b2129fe2d
Create Date: 2026-01-08 11:00:44.622105

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '31306f7b8b19'
down_revision = '255b2129fe2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('defects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Label', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('Crushed', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('Discolored', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('weight', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_Defect', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('image_url', sa.String(length=255), nullable=True))
        batch_op.drop_column('defect_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('defects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('defect_type', mysql.ENUM('Normal', 'Label', 'Crushed', 'Discolored', 'weight'), nullable=False))
        batch_op.drop_column('image_url')
        batch_op.drop_column('is_Defect')
        batch_op.drop_column('weight')
        batch_op.drop_column('Discolored')
        batch_op.drop_column('Crushed')
        batch_op.drop_column('Label')

    # ### end Alembic commands ###
