"""Feat: 불량 테이블

Revision ID: 5e55119daa6f
Revises: 9b2080fef7f0
Create Date: 2025-12-29 12:24:09.606170

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5e55119daa6f'
down_revision = '9b2080fef7f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('defects', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.VARBINARY(length=255),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('defect_type',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.Enum('LABEL', 'CONTAINER', 'COLOR', 'WEIGHT', name='defect_types'),
               existing_nullable=True)
        batch_op.alter_column('machine_number',
               existing_type=mysql.INTEGER(),
               nullable=False)

    with op.batch_alter_table('rejection_rates', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.VARBINARY(length=255),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('machine_number',
               existing_type=mysql.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rejection_rates', schema=None) as batch_op:
        batch_op.alter_column('machine_number',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=sa.VARBINARY(length=255),
               existing_nullable=True)

    with op.batch_alter_table('defects', schema=None) as batch_op:
        batch_op.alter_column('machine_number',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('defect_type',
               existing_type=sa.Enum('LABEL', 'CONTAINER', 'COLOR', 'WEIGHT', name='defect_types'),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=sa.VARBINARY(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###
