"""empty message

Revision ID: 83267c994831
Revises: bfaf703aa8d4
Create Date: 2025-12-29 14:36:48.301622

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '83267c994831'
down_revision = 'bfaf703aa8d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sensors', schema=None) as batch_op:
        batch_op.drop_column('temperature')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sensors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('temperature', mysql.FLOAT(), nullable=True))

    # ### end Alembic commands ###
