"""empty message

Revision ID: 9b2080fef7f0
Revises: be770e7ad89e
Create Date: 2025-12-29 11:38:43.495345

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9b2080fef7f0'
down_revision = 'be770e7ad89e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('defects')
    with op.batch_alter_table('sensors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('temperature_DS18B20', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sensors', schema=None) as batch_op:
        batch_op.drop_column('temperature_DS18B20')

    op.create_table('defects',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.VARBINARY(length=255), nullable=True),
    sa.Column('defect_type', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('machine_number', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['machine_number'], ['machines.id'], name=op.f('FK135g6837gx37bng2v0thlnbgg')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
