"""empty message

Revision ID: b1dda2786261
Revises: 9b2080fef7f0
Create Date: 2025-12-29 15:57:45.791088

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b1dda2786261'
down_revision = '9b2080fef7f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('defects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('defect_type', sa.Enum('Label', 'Crushed', 'Discolored', 'weight', name='defect_types'), nullable=True),
    sa.Column('machine_number', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['machine_number'], ['machines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('danger_score')
    with op.batch_alter_table('sensors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('temperature', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sensors', schema=None) as batch_op:
        batch_op.drop_column('temperature')

    op.create_table('danger_score',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('dangerScore', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('machine_number', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['machine_number'], ['machines.id'], name=op.f('danger_score_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('defects')
    # ### end Alembic commands ###
