"""empty message

Revision ID: be770e7ad89e
Revises: cfb994d99679
Create Date: 2025-12-29 11:14:34.053488

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'be770e7ad89e'
down_revision = 'cfb994d99679'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('machine_number', sa.Integer(), nullable=True),
    sa.Column('level', sa.Enum('NORMAL', 'WARNING', 'EMERGENCY', name='alert_level'), nullable=False),
    sa.Column('danger_score', sa.Float(), nullable=True),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('message', sa.String(length=255), nullable=False),
    sa.Column('snapshot', mysql.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['machine_number'], ['machines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alert_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alert_events_acknowledged_at'), ['acknowledged_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_alert_events_ended_at'), ['ended_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_alert_events_level'), ['level'], unique=False)
        batch_op.create_index(batch_op.f('ix_alert_events_machine_number'), ['machine_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_alert_events_started_at'), ['started_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alert_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alert_events_started_at'))
        batch_op.drop_index(batch_op.f('ix_alert_events_machine_number'))
        batch_op.drop_index(batch_op.f('ix_alert_events_level'))
        batch_op.drop_index(batch_op.f('ix_alert_events_ended_at'))
        batch_op.drop_index(batch_op.f('ix_alert_events_acknowledged_at'))

    op.drop_table('alert_events')
    # ### end Alembic commands ###
