"""empty message

Revision ID: bfaf703aa8d4
Revises: 1dd468eebc38
Create Date: 2025-12-29 14:24:33.893297

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfaf703aa8d4'
down_revision = '1dd468eebc38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('danger_score', schema=None) as batch_op:
        batch_op.add_column(sa.Column('machine_number', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'machines', ['machine_number'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('danger_score', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('machine_number')

    # ### end Alembic commands ###
