"""empty message

Revision ID: d7d2782bcef8
Revises: 83267c994831
Create Date: 2025-12-29 14:58:31.801477

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd7d2782bcef8'
down_revision = '83267c994831'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alert_events', schema=None) as batch_op:
        batch_op.alter_column('level',
               existing_type=mysql.ENUM('EMERGENCY', 'NORMAL', 'WARNING'),
               type_=sa.Enum('NORMAL', 'WARNING', 'EMERGENCY', name='alert_level'),
               existing_nullable=False)
        batch_op.drop_index(batch_op.f('idx_alert_ack'))
        batch_op.drop_index(batch_op.f('idx_alert_ended'))
        batch_op.drop_index(batch_op.f('idx_alert_level'))
        batch_op.drop_index(batch_op.f('idx_alert_machine'))
        batch_op.drop_index(batch_op.f('idx_alert_started'))

    with op.batch_alter_table('sensors', schema=None) as batch_op:
        batch_op.drop_column('temperature')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sensors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('temperature', mysql.FLOAT(), nullable=True))

    with op.batch_alter_table('alert_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_alert_started'), ['started_at'], unique=False)
        batch_op.create_index(batch_op.f('idx_alert_machine'), ['machine_number'], unique=False)
        batch_op.create_index(batch_op.f('idx_alert_level'), ['level'], unique=False)
        batch_op.create_index(batch_op.f('idx_alert_ended'), ['ended_at'], unique=False)
        batch_op.create_index(batch_op.f('idx_alert_ack'), ['acknowledged_at'], unique=False)
        batch_op.alter_column('level',
               existing_type=sa.Enum('NORMAL', 'WARNING', 'EMERGENCY', name='alert_level'),
               type_=mysql.ENUM('EMERGENCY', 'NORMAL', 'WARNING'),
               existing_nullable=False)

    # ### end Alembic commands ###
